apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  namespace: jian-test
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: jian-test
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: net-tool
spec:
  containers:
  - name: net-tool
    image: liujian82/netswissknife
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]

